name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup docs directory
        run: |
          # docs 디렉토리 생성 및 준비
          mkdir -p docs/api/static
          
          # index.html을 docs로 복사
          cp index.html docs/
          
          # api/static 내용을 docs/api/static으로 복사
          cp -r api/static/* docs/api/static/ || true
          
          # CNAME 파일 생성
          echo "aof.wvl.co.kr" > docs/CNAME
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Update docs directory for GitHub Pages" || true
          git push