name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup files for GitHub Pages
        run: |
          # CNAME 파일 설정 (없으면 생성)
          if [ -f "CNAME" ]; then
            echo "CNAME 파일이 존재합니다."
          else
            echo "aof.wvl.co.kr" > CNAME
            echo "CNAME 파일을 생성했습니다."
          fi
          
          # 필요한 디렉토리 구조 확인
          mkdir -p api/static 2>/dev/null || true
          
          # index.html 파일 확인
          if [ ! -f "index.html" ]; then
            echo "index.html 파일이 없습니다. 기본 리다이렉트 파일을 생성합니다."
            cat > index.html << EOF
<!DOCTYPE html>
<html><head><meta charset="UTF-8"><meta http-equiv="refresh" content="1;url=api/static/index.html" /><title>AllOneFlow</title></head>
<body><div style="text-align:center;"><h1>AllOneFlow</h1><p>시스템으로 이동 중입니다...</p><a href="api/static/index.html">바로가기</a></div></body>
</html>
EOF
          fi
          
          # api/static 디렉토리 내용 확인
          if [ ! -f "api/static/index.html" ]; then
            echo "api/static/index.html 파일이 없습니다."
          fi
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: .
          clean: true